# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = "ï„ "
"termite" = "ï„ "
"terminal" = "ï„ "
"kitty" = "ï˜š"
"github" = "ï„“"
"rust" = "î¨"
"google" = "ï† "
"private browsing" = "ïˆ›"
"firefox" = "ï‰©"
"chrome" = "ï‰¨"
"file manager" = "ï¼"
"nautilus" = "ï¼"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ïœ˜"
"libreoffice" = "ï£…"
"nvim" = "îŸ…"
"gthumb" = "ï€¾"
"eog" = "ï€¾"
"menu" = "ï¡œ"
"calculator" = "ï—«"
"transmission" = "ï€™"
"videostream" = "ï˜˜"
"mpv" = "ï¢€"
"vlc" = "ï¢€"
"mplayer" = "ï¢€"
"music" = "ï€"
"disk usage" = "ïŸ‰"
".pdf" = "ïœ¤"
"spotify" = "ï†¼"
"gnome" = "ï«"
"discord" = "ï¡§"
"bitwarden" = "ï ½"
"steam" = "ï†¶"
"snapper" = "ïŸ‰"
"helvum" = "ïŸŠ"
"code" = "ï¬"

[other]
"fallback_icon" = "ğŸ¤¨"
